loginAndRegist/App/views/main.py
from flask import Blueprint,render_template,request,current_app,redirect,url_for
from App.models import Posts,User,Superuser
from App.extensions import cache

main = Blueprint('main',__name__)

@main.route('/')
def index():
    return redirect(url_for('main.page_show',page=1))


@main.route('/page_show/<int:page>/')
# @cache.memoize(timeout=100)
# @cache.cached(timeout=100,key_prefix='index')
def page_show(page):
    print('能看到我几次')
    pagination = Posts.query.filter_by(pid=0).order_by(Posts.timestamp.desc()).paginate(page,current_app.config['PAGE_NUM'],False)
    
    data = pagination.items #返回当前page的所有数据
    print(pagination)
    return render_template('main/index.html',data=data,pagination=pagination)






#测试多对多的使用
@main.route('/test/')
def test():
    print('xxxxx')
    u = User.query.get(1)
    p = Posts.query.get(7)
    #id1用户收藏1号帖子
    # u.favorite.append(p)

    #查看用户1收藏了那些帖子
    # print(u.favorite.all())

    #1号帖子被哪些用户 收藏了
    # print(p.users.all())

    #取消收藏
    # u.favorite.remove(p)
    return '测试'

loginAndRegist/App/views/posts.py
from flask import Blueprint,render_template,flash,redirect,url_for,jsonify,request
from App.forms import Posts as PostsForm
from flask_login import current_user
from App.models import Posts
from App.extensions import db,file
import os
from .user import *

posts = Blueprint('posts',__name__)


#发表帖子的路由
@posts.route('/send_posts/',methods=['GET','POST'])
def send_posts():
    form= PostsForm()
    
    if form.validate_on_submit():
        if current_user.is_authenticated:
            shuffix = os.path.splitext(form.file.data.filename)[-1]
            #生成随机的图片名
            while True:
                newName = new_name(shuffix)
                if not os.path.exists(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],newName)):
                    break
            file.save(form.file.data,name=newName)
            #判断用户更改头像 原头像是否为默认 不是则将原图片删除
            
            #执行缩放
            img = Image.open(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],newName))
            img.thumbnail((300,300))
            #保存新的图片名称为新的图片的s_newname
            img.save(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],'s_'+newName))


            #拿到真正实例化的user对象
            u = current_user._get_current_object()
            file.save(form.file.data,name=newName)
            p = Posts(selfread=form.selfread.data,content=form.content.data,image=newName,
                user=u,title=form.title.data,director=form.director.data,characters=form.characters.data)
            db.session.add(p)
            flash('电影发表成功!!!')
            return redirect(url_for('main.index'))
        else:
            flash('您还没有登录 请前去登录在发表')
            return redirect(url_for('user.login'))
    return render_template('posts/send_posts.html',form=form)


#收藏 取消收藏
@posts.route('/favorite/<pid>')
def favorite(pid):
    try:
        if current_user.is_favorite(pid):
            print('取消收藏')
            current_user.remove_favorite(pid)
        else:
            print('添加收藏')
            current_user.add_favorite(pid)
        return jsonify({'res':200})
    except:
        return jsonify({'res':500})

@posts.route('/show_posts/<pid>')
def show_posts(pid):
    Post = Posts.query.filter_by(id=pid)[0]
    img=Post.image
    title=Post.title
    content=Post.content
    selfread=Post.selfread
    director=Post.director
    characters=Post.characters
    uid=Post.uid
    postUser=User.query.filter_by(id=uid)[0]
    icon=postUser.icon
    userName=postUser.username
    print(userName)
    # data =showPost.items #返回当前page的所有数据
    # print(pagination)
    return render_template('posts/show_posts.html',
        img=img,selfread=selfread
        ,title=title,content=content,userIcon=icon,username=userName,dirs=director,cha=characters)

# @posts.route('/search_posts/',methods=['POST','GET'])
# def search_posts():
#     if methods=='POST'
@posts.route('/search_posts/',methods=['GET','POST'])
def index():
    return redirect(url_for('posts.search_posts',page=1))

#搜索返回页
@posts.route('/search_posts/<int:page>',methods=['GET','POST'])
def search_posts(page):
    # print('能看到我几次')
    keyword=request.form.get('keyword')
    print(keyword)
    if keyword:
        keyword=str(keyword)
        pagination = Posts.query.filter(Posts.title.contains(keyword)).order_by(Posts.timestamp.desc()).paginate(page,current_app.config['PAGE_NUM'],False)
    else:
        pagination = Posts.query.filter_by(pid=0).order_by(Posts.timestamp.desc()).paginate(page,current_app.config['PAGE_NUM'],False)
        flash('未找到匹配项，您可以查看其他电影')
    data = pagination.items #返回当前page的所有数据
    print(pagination)
    return render_template('posts/search_posts.html',data=data,pagination=pagination,title='搜索结果为',keyword='关键词%s'%(keyword))

loginAndRegist/App/views/superuser.py
from flask import Blueprint,render_template,flash,redirect,url_for,current_app
from App.models import Superuser
from App.forms import Login
from flask_login import login_user,logout_user,login_required,current_user


superuser=Blueprint('superuser',__name__)
#注册
@superuser.route('/register/',methods=['GET','POST'])
def register():
    form = Register()
    if form.validate_on_submit():
        #实例化user模型类
        u = Superuser(username=form.username.data,password=form.password.data)
        db.session.add(u)
        db.session.commit()
        #生成token
        # token = u.generate_token()
        
    return render_template('superuser/login.html',form=form)


#登录
@superuser.route('/adminlogin/',methods=['GET','POST'])
def adminlogin():
    form = Login()
    if form.validate_on_submit():
        u=Superuser.query.filter_by(username=form.username.data)
        if not u:
            flash('管理员不存在')
        elif u.check_password_hash(form.password.data):
            flash('登录成功！')
            login_user(u,remember=form.remember.data)
        else:
            flash('请输入正确的密码')
    return render_template('superuser/login.html',form=form)

loginAndRegist/App/views/user.py
from flask import Blueprint,render_template,flash,redirect,url_for,current_app
from App.models import User
from App.models import Superuser
from App.forms import Register,Login,Icon,Change_email,Change_password
from App.extensions import db,file
from App.email import send_mail
from flask_login import login_user,logout_user,login_required,current_user
import os
from PIL import Image


user = Blueprint('user',__name__)

#注册
@user.route('/register/',methods=['GET','POST'])
def register():
    form = Register()
    if form.validate_on_submit():
        #实例化user模型类
        u = User(username=form.username.data,password=form.password.data,email=form.email.data)
        db.session.add(u)
        db.session.commit()
        #获取刚创建的user的id，并和superuser关联起来
        u=User.query.filter_by(username=form.username.data)[0]
        uid=u.id
        s=Superuser.query.filter_by(id=1)[0]
        s.users.append(u)
        # db.session.add(s)
        db.session.commit()
        #生成token
        token = u.generate_token()
        #发送邮件
        send_mail('邮件激活',form.email.data,'activate', username='zhangsan',token=token)
        #提示用户注册称该
        flash('注册成功请去邮箱中激活')
        #跳转到登录页面
        return redirect(url_for('user.login'))
    return render_template('user/register.html',form=form)

@user.route('/activate/<token>/')
def activate(token):
    if User.check_token(token):
        flash('激活成功 请登录')
        return redirect(url_for('user.login'))
    else:
        flash('激活失败')
        return redirect(url_for('main.index'))


#登录
#加一个时间的验证  如果输入错误超过三次  把激活改为False
@user.route('/login/',methods=['GET','POST'])
def login():
    form = Login()
    if form.validate_on_submit():
        u = User.query.filter_by(username=form.username.data).first()
        if not u:
            flash('该用户不存在')
        elif not u.confirm:
            flash('该用户还没激活！！！')
        elif u.check_password_hash(form.password.data):
            flash('登录成功！')
            login_user(u,remember=form.remember.data)
            return redirect(url_for('main.index'))
        else:
            flash('请输入正确的密码')
    return render_template('user/login.html',form=form)

#退出登录
@user.route('/logout/')
def logout():
    logout_user()
    flash('退出成功！')
    return redirect(url_for('main.index'))



"""
@user.route('/test/')
@login_required
def test():
    return '我必须登录以后才能访问'
    #需求  当用户反问了必须登录才能访问的路由的时候  在登录以后自动跳转到上次访问的路由地址
"""
#生成随机的名字的函数
def new_name(shuffix,length=32):
    import string,random
    myStr = string.ascii_letters+'0123456789'
    return ''.join(random.choice(myStr) for i in range(length))+shuffix

#修改头像
@user.route('/change_icon/',methods=['GET','POST'])
def change_icon():
    form = Icon()
    if form.validate_on_submit():
        shuffix = os.path.splitext(form.file.data.filename)[-1]
        #生成随机的图片名
        while True:
            newName = new_name(shuffix)
            if not os.path.exists(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],newName)):
                break
        file.save(form.file.data,name=newName)
        #判断用户更改头像 原头像是否为默认 不是则将原图片删除
        if current_user.icon != 'default.jpg':
            os.remove(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],current_user.icon))

        #执行缩放
        img = Image.open(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],newName))
        img.thumbnail((300,300))
        #保存新的图片名称为新的图片的s_newname
        img.save(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],'s_'+newName))

        current_user.icon = newName
        db.session.add(current_user)
        flash('头像上传成功')
    img_url = file.url(current_user.icon)
    return render_template('user/change_icon.html',form=form,img_url=img_url)
#修改邮箱
@user.route('/change_email/',methods=['GET','POST'])
@login_required
def change_email():
    form = Change_email()
    if form.validate_on_submit():
        newEmail=form.email.data
        #判断新旧邮箱是否想同
        if current_user.email !=newEmail:
            # send_mail('邮件激活',newEmail,'activate', username='zhangsan',token=token)
            current_user.email=newEmail
            db.session.commit()
        else:
            flash('新邮箱不能与就邮箱一致')
            return render_template('user/change_icon.html',form=form)
    return render_template('user/change_email.html',form=form)


@user.route('/change_password/',methods=['GET','POST'])
@login_required
def change_password():
    form = Icon()
    if form.validate_on_submit():
        shuffix = os.path.splitext(form.file.data.filename)[-1]
        #生成随机的图片名
        while True:
            newName = new_name(shuffix)
            if not os.path.exists(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],newName)):
                break
        file.save(form.file.data,name=newName)
        #判断用户更改头像 原头像是否为默认 不是则将原图片删除
        if current_user.icon != 'default.jpg':
            os.remove(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],current_user.icon))

        #执行缩放
        img = Image.open(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],newName))
        img.thumbnail((300,300))
        #保存新的图片名称为新的图片的s_newname
        img.save(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],'s_'+newName))

        current_user.icon = newName
        db.session.add(current_user)
        flash('头像上传成功')
    img_url = file.url(current_user.icon)
    return render_template('user/change_icon.html',form=form,img_url=img_url)

loginAndRegist/App/templates/common/base.html
{% extends 'bootstrap/base.html' %}
{% block title %}
    使用bootsrap
{% endblock %}
{% block navbar %}
    <nav class="navbar navbar-inverse" style="border-radius: 0px;">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-film" aria-hidden="true"></span></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{{ url_for('main.index') }}">首页 <span
                            class="sr-only">(current)</span></a></li>
                    <li class="active"><a href="{{ url_for('superuser.adminlogin') }}">管理员登陆 <span
                            class="sr-only">(current)</span></a></li>
                    <li class="active"><a href="{{ url_for('main.index') }}">欧美电影 <span
                            class="sr-only">(current)</span></a></li>
                    <li class="active"><a href="{{ url_for('main.index') }}">日韩电影<span
                            class="sr-only">(current)</span></a></li>
                    <li class="active"><a href="{{ url_for('main.index') }}">国产电影<span
                                class="sr-only">(current)</span></a></li>
                    <li class="active"><a href="{{ url_for('main.index') }}">印度电影<span
                                    class="sr-only">(current)</span></a></li>
                        {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('posts.send_posts') }}">上传电影</a></li>
                    {%endif%}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li><img src="{{ url_for('static',filename=current_user.icon) }}" alt=""></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">个人中心 <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">个人信息</a></li>
                                <li><a href="{{ url_for('user.change_icon') }}">修改头像</a></li>
                                <li><a href="{{ url_for('user.change_password') }}">修改密码</a></li>
                                <li><a href="{{ url_for('user.change_email') }}">修改个人信息</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{{ url_for('user.logout') }}">退出登录</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{{ url_for('user.register') }}">注册</a></li>
                        <li><a href="{{ url_for('user.login') }}">登录</a></li>
                    {% endif %}
                </ul>
<!-- 下拉菜单 -->
            <!-- <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                aria-haspopup="true"
                aria-expanded="false">个人中心 <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">个人信息</a></li>
                    <li><a href="{{ url_for('user.change_icon') }}">修改头像</a></li>
                    <li><a href="#">修改密码</a></li>
                    <li><a href="#">修改邮箱</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{{ url_for('user.logout') }}">退出登录</a></li>
                </ul>
            </li>

            <li><a href="{{ url_for('user.register') }}">注册</a></li>
            <li><a href="{{ url_for('user.login') }}">登录</a></li>

            </ul> -->

                <form class="navbar-form navbar-right" action="{{ url_for('posts.search_posts',page=1) }}" method="POST">
                    <div class="form-group">
                        <input type="text" name="keyword" class="form-control" placeholder="请输入电影名称" value="">
                    </div>
                    <button type="submit"   class="btn btn-default">搜索</button>
                </form>
            </div><!-- /.navbar-collapse -->
        </div>
    </nav>


{% endblock %}
{% block content -%}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <strong></strong>{{ message }}
            </div>
        {% endfor %}
        {% block page_content %}

        {% endblock %}
    </div>
{%- endblock content %}
{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.locale('zh-CN') }}
{% endblock %}

loginAndRegist/App/templates/common/pagemacro.html
{% macro page_show(pagination,urlFor) %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li {% if not pagination.has_prev %} class="disabled" {% endif %}>
                <a {% if pagination.has_prev %} href="{{ url_for(urlFor,page=pagination.prev_num) }}" {% endif %} aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% for page in pagination.iter_pages() %}
                {% if page %}
                    <li {% if page == pagination.page %}class="active"{% endif %}><a href="{{ url_for(urlFor,page=page) }}">{{ page }}</a></li>
                {% else %}
                    <li class="disabled"><a>...</a></li>
                {% endif %}
            {% endfor %}

            <li {% if not pagination.has_next %} class="disabled" {% endif %}>
                <a {% if pagination.next_prev %} href="{{ url_for(urlFor,page=pagination.next_num) }}" {% endif %} aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endmacro %}