loginAndRegist/App/models/posts.py
from App.extensions import db
from datetime import datetime



class Posts(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    content = db.Column(db.Text)
    title=db.Column(db.String(50),default='电影名称')
    pid = db.Column(db.Integer,default=0)
    image = db.Column(db.String(255),default='defaultImage,')
    timestamp = db.Column(db.DateTime,default=datetime.utcnow)
    uid = db.Column(db.Integer,db.ForeignKey('user.id'))
    characters=db.Column(db.String(255),default='暂无详细演员信息')#演员名称
    director=db.Column(db.String(255),default="暂无详细导演信息")
    selfread=db.Column(db.Text,default="暂无作者观后感")
    # category=db.Column(db.String(255),default='暂未分类')#分类

loginAndRegist/App/forms/posts.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField,SubmitField,FileField
from wtforms.validators import DataRequired,Length
from flask_wtf.file import FileAllowed,FileRequired
from App.extensions import file
# class Posts(FlaskForm):
#     content = TextAreaField('发表博客',validators=[DataRequired(message='帖子不可以为空'),Length(min=6,max=100,message='帖子内容为6-100个字')],render_kw={'placeholder':'发表你此刻的感想...','style':'resize:none;'})
#     # submit = SubmitField('发表')

class Posts(FlaskForm):
    title = TextAreaField('电影名称',validators=[DataRequired(message='名称不可以为空'),Length(min=1,max=100,message='帖子内容为6-100个字')],render_kw={'placeholder':'请输入电影名称...','style':'resize:none;'})
    #演员名称
    characters=TextAreaField('演员名称',validators=[DataRequired(message='名称不可以为空'),Length(min=1,max=100,message='帖子内容为6-100个字')],render_kw={'placeholder':'请输入演员信息','style':'resize:none;'})
    director=TextAreaField('导演名称',validators=[DataRequired(message='名称不可以为空'),Length(min=1,max=100,message='帖子内容为6-100个字')],render_kw={'placeholder':'请输入导演名字','style':'resize:none;'})
    # category=TextAreaField('电影分类',validators=[DataRequired(message='名称不可以为空'),Length(min=1,max=100,message='帖子内容为6-100个字')],render_kw={'placeholder':'请填写分类，例如','style':'resize:none;'})#分类
    content = TextAreaField('电影简介',validators=[DataRequired(message='内容不可以为空'),Length(min=100,max=200,message='帖子内容为100-200个字')],render_kw={'placeholder':'请输入电影简介...','style':'resize:none;'})
    selfread=TextAreaField('电影观后感',validators=[DataRequired(message='内容不可以为空'),Length(min=100,max=200,message='帖子内容为100-200个字')],render_kw={'placeholder':'发表你此刻的感想...','style':'resize:none;'})
    file = FileField('上传电影海报',validators=[FileAllowed(file,message='只允许上传图片'),FileRequired(message='文件不能为空')])
    submit = SubmitField('上传')

loginAndRegist/App/views/posts.py
from flask import Blueprint,render_template,flash,redirect,url_for,jsonify,request
from App.forms import Posts as PostsForm
from flask_login import current_user
from App.models import Posts
from App.extensions import db,file
import os
from .user import *

posts = Blueprint('posts',__name__)


#发表帖子的路由
@posts.route('/send_posts/',methods=['GET','POST'])
def send_posts():
    form= PostsForm()
    
    if form.validate_on_submit():
        if current_user.is_authenticated:
            shuffix = os.path.splitext(form.file.data.filename)[-1]
            #生成随机的图片名
            while True:
                newName = new_name(shuffix)
                if not os.path.exists(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],newName)):
                    break
            file.save(form.file.data,name=newName)
            #判断用户更改头像 原头像是否为默认 不是则将原图片删除
            
            #执行缩放
            img = Image.open(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],newName))
            img.thumbnail((300,300))
            #保存新的图片名称为新的图片的s_newname
            img.save(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],'s_'+newName))


            #拿到真正实例化的user对象
            u = current_user._get_current_object()
            file.save(form.file.data,name=newName)
            p = Posts(selfread=form.selfread.data,content=form.content.data,image=newName,
                user=u,title=form.title.data,director=form.director.data,characters=form.characters.data)
            db.session.add(p)
            flash('电影发表成功!!!')
            return redirect(url_for('main.index'))
        else:
            flash('您还没有登录 请前去登录在发表')
            return redirect(url_for('user.login'))
    return render_template('posts/send_posts.html',form=form)


#收藏 取消收藏
@posts.route('/favorite/<pid>')
def favorite(pid):
    try:
        if current_user.is_favorite(pid):
            print('取消收藏')
            current_user.remove_favorite(pid)
        else:
            print('添加收藏')
            current_user.add_favorite(pid)
        return jsonify({'res':200})
    except:
        return jsonify({'res':500})

@posts.route('/show_posts/<pid>')
def show_posts(pid):
    Post = Posts.query.filter_by(id=pid)[0]
    img=Post.image
    title=Post.title
    content=Post.content
    selfread=Post.selfread
    director=Post.director
    characters=Post.characters
    uid=Post.uid
    postUser=User.query.filter_by(id=uid)[0]
    icon=postUser.icon
    userName=postUser.username
    print(userName)
    # data =showPost.items #返回当前page的所有数据
    # print(pagination)
    return render_template('posts/show_posts.html',
        img=img,selfread=selfread
        ,title=title,content=content,userIcon=icon,username=userName,dirs=director,cha=characters)

# @posts.route('/search_posts/',methods=['POST','GET'])
# def search_posts():
#     if methods=='POST'
@posts.route('/search_posts/',methods=['GET','POST'])
def index():
    return redirect(url_for('posts.search_posts',page=1))

#搜索返回页
@posts.route('/search_posts/<int:page>',methods=['GET','POST'])
def search_posts(page):
    # print('能看到我几次')
    keyword=request.form.get('keyword')
    print(keyword)
    if keyword:
        keyword=str(keyword)
        pagination = Posts.query.filter(Posts.title.contains(keyword)).order_by(Posts.timestamp.desc()).paginate(page,current_app.config['PAGE_NUM'],False)
    else:
        pagination = Posts.query.filter_by(pid=0).order_by(Posts.timestamp.desc()).paginate(page,current_app.config['PAGE_NUM'],False)
        flash('未找到匹配项，您可以查看其他电影')
    data = pagination.items #返回当前page的所有数据
    print(pagination)
    return render_template('posts/search_posts.html',data=data,pagination=pagination,title='搜索结果为',keyword='关键词%s'%(keyword))

loginAndRegist/App/templates/posts/search_posts.html
{% extends 'common/base.html' %}
{% block title %}
    {{title}}
{% endblock %}
{% block page_content %}
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- 论波图点 -->
        <!-- <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol> -->

        <!-- 论波图 -->
        <!-- <div class="carousel-inner" role="listbox">
            {% for i in range(1,4) %}
                <div class="item {% if loop.first %}active{% endif %}" style="height: 400px;">
                    <img src="{{ url_for('static',filename='img/'+i|string+'.jpg') }}" alt="...">
                    <div class="carousel-caption">
                        
                    </div>
                </div>
            {% endfor %}

        </div> -->

        <!-- Controls -->
        <!-- <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div> -->
    <h3>{{keyword}}</h3>
    {#  以下为帖子的展示页面  #}
    
    {% for posts in data %}
        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                    <img height="150" class="media-object"
                         src="{{ url_for('static',filename='upload/s_'+posts.image) }}"
                         alt="{{ posts.user.username }}">
                </a>
            </div>
            <div class="media-body">
                <a href="{{ url_for('posts.show_posts',pid=posts.id) }}" ><h3 class="media-heading">{{ posts.title }}<span
                        style="float: right;font-size: 14px">{{ moment(posts.timestamp).fromNow() }}</span></h3></a>
                {{ posts.content|safe }}
                {% if current_user.is_authenticated %}
                    <div onclick="favorite({{ posts.id }})" id="{{ posts.id }}" url="{{ url_for('posts.favorite',pid=posts.id) }}">{% if current_user.is_favorite(posts.id) %}取消收藏{% else %}收藏{% endif %}</div>
                {% endif %}
            </div>
        </div>
        
    {% endfor %}

    {#  导入分页的macro  #}
    {% from 'common/pagemacro.html' import page_show %}
    {{ page_show(pagination,'main.page_show') }}
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
        function favorite(pid){
            var doc = $('#'+pid);
            $.get(doc.attr('url'),function (data) {
                console.log('执行',data)
                if(doc.html() == '收藏'){
                    doc.html('取消收藏')
                }else{
                    doc.html('收藏')
                }
            })
        }
    </script>
{% endblock %}

loginAndRegist/App/templates/posts/send_posts.html
{% extends 'common/base.html' %}
{% block title %}
    发布你喜爱的电影
{% endblock %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block scripts %}
    {{ super() }}
    <script src="//cdn.ckeditor.com/4.4.6/standard/ckeditor.js"></script>
{% endblock %}
{% block page_content %}
<h2>快来创建属于你自己的喜爱的电影吧！！！</h2>
<img src="{{ img_url }}" alt="" width="300" border-radius='300px'>
{{ wtf.quick_form(form) }}

    <!-- <div class="page-header"><h1>上传电影信息</h1></div>
    <form action="{{ url_for('posts.send_posts') }}" method="post">
        {{ form.csrf_token }}
        {{ form.content(class="ckeditor") }}
        <button type="submit" class="btn btn-success">发表</button>
        {% if  form.content.errors%}
            <div style="float: right;color: red;">{{ form.content.errors.0 }}</div>
        {% endif %}
        
    </form> -->
    
    <!-- <form action="{{ url_for('posts.send_posts') }}">
        <input type="text" value='电影名称'><br>
        <div width="500px" height="300px" border='solid 1px black'>
            <input type="text" value='电影名称' ><br>
        </div>
        
        <input type="text" value='电影名称'><br>
    </form> -->
 
{% endblock %}

loginAndRegist/App/templates/posts/show_posts.html
<!-- 展示电影详细信息页面 -->
{% extends 'common/base.html' %}
{% block title %}
    {{title}}
{% endblock %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block page_content %}
    <!-- <img src="{{ url_for('static',filename='upload/s_'+img) }}" alt=""> -->

<div class="media">
    <a class="media-left" href="#">
        <img class="media-object" src="{{ url_for('static',filename='upload/s_'+img) }}"
             alt="媒体对象">
    </a>
    <div class="media-body">
        <h1 class="media-heading">{{title}}</h1>
        {{content}}
        <h5 style="color: red">演员表：</h5><h2 class="media-heading">{{cha}}</h2> <!-- 演员表-->
        <h5 style="color: blueviolet">演员表：<h1 class="media-heading">{{dirs}}</h1> <!-- 导演表-->
        <!-- <h1 class="media-heading">{分类}</h1> 分类 -->
    </div>
</div>
<a>{{userName}}</a>
<div class="media">
    <a class="media-left" href="#">
        <img class="media-object" src="{{ url_for('static',filename='upload/s_'+userIcon) }}" style="height: 80px; width: 80px;"
             alt="{{userName}}">
    </a>

    <div class="media-body">
        <h4 class="media-heading">电影简介</h4>
        <h2>{{selfread}}</h2>
        
        <!-- <div class="media">
            <a class="media-left" href="#">
                <img class="media-object" src="/wp-content/uploads/2014/06/64.jpg"
                     alt="媒体对象">
            </a>
            <div class="media-body">
                <h4 class="media-heading">媒体标题</h4>
                这是一些示例文本。这是一些示例文本。
                这是一些示例文本。这是一些示例文本。
                这是一些示例文本。这是一些示例文本。
                这是一些示例文本。这是一些示例文本。
                这是一些示例文本。这是一些示例文本。
            </div>
        </div> -->
    </div>
</div>

{% endblock %}